<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div>
     <form action="/answer" method="post">
        <input name="ID" placeholder="Id клиента">
        <input type="submit" value="Answer me">
    </form>

</div>
</body>
</html>